"use client";

import { useMemo, useState } from "react";
import { Activity, CheckCircle2, Database, GitPullRequest, ShieldAlert, ShieldCheck } from "lucide-react";
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from "recharts";
import RepoAuditScanner, { AuditResult } from "../components/RepoAuditScanner";
import VulnerabilityDiffViewer from "../components/VulnerabilityDiffViewer";

const distribution = [
  { name: "Critical", value: 2, color: "#ef4444" },
  { name: "High", value: 3, color: "#f97316" },
  { name: "Medium", value: 5, color: "#eab308" },
  { name: "Low", value: 7, color: "#22c55e" }
];

export default function DashboardPage() {
  const [audit, setAudit] = useState<AuditResult | null>(null);
  const [backendOnline, setBackendOnline] = useState<boolean | null>(null);

  const metrics = useMemo(() => {
    const findings = audit?.findings ?? [];
    const critical = findings.filter((item) => item.severity === "critical").length;
    const high = findings.filter((item) => item.severity === "high").length;
    const score = audit?.risk_score ?? 82;
    return { critical, high, score, findings };
  }, [audit]);

  return (
    <main className="mx-auto min-h-screen max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
      <header className="mb-8 flex flex-col gap-5 border-b border-slate-800 pb-6 md:flex-row md:items-center md:justify-between">
        <div className="flex items-center gap-4">
          <div className="rounded-2xl border border-teal-400/30 bg-teal-400/10 p-3 text-teal-300">
            <ShieldCheck size={30} />
          </div>
          <div>
            <p className="text-xs font-semibold uppercase tracking-[0.24em] text-teal-300">Security Operations Platform</p>
            <h1 className="mt-1 text-2xl font-bold tracking-tight text-white sm:text-3xl">Aegis Autonomous Auditor</h1>
          </div>
        </div>
        <div className="flex items-center gap-2 rounded-full border border-slate-700 bg-slate-900/70 px-4 py-2 text-sm text-slate-300">
          <span className={`h-2 w-2 rounded-full ${backendOnline === false ? "bg-amber-400" : "bg-emerald-400"}`} />
          {backendOnline === false ? "Mock telemetry active" : backendOnline === true ? "Agent engine connected" : "Checking agent engine"}
        </div>
      </header>

      <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <MetricCard label="Security Health" value={`${metrics.score}/100`} note="Weighted policy & dependency score" icon={<ShieldCheck />} tone="emerald" />
        <MetricCard label="Critical Exposure" value={String(metrics.critical)} note="Immediate remediation required" icon={<ShieldAlert />} tone="red" />
        <MetricCard label="High-Risk Findings" value={String(metrics.high)} note="Prioritize in current sprint" icon={<Activity />} tone="orange" />
        <MetricCard label="Automated Patches" value={audit ? String(audit.findings.filter((f) => f.patch).length) : "3"} note="Generated by remediation agent" icon={<GitPullRequest />} tone="blue" />
      </section>

      <section className="mt-6 grid gap-6 xl:grid-cols-[1.45fr_0.85fr]">
        <RepoAuditScanner onAuditComplete={setAudit} onBackendState={setBackendOnline} />
        <aside className="rounded-2xl border border-slate-800 bg-slate-950/70 p-5 shadow-panel">
          <div className="mb-3 flex items-center justify-between">
            <div>
              <h2 className="font-semibold text-white">Risk Distribution</h2>
              <p className="mt-1 text-sm text-slate-400">Latest observed security posture</p>
            </div>
            <Database className="text-slate-500" size={20} />
          </div>
          <div className="h-56">
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie data={distribution} dataKey="value" nameKey="name" innerRadius={55} outerRadius={86} paddingAngle={3}>
                  {distribution.map((entry) => <Cell key={entry.name} fill={entry.color} />)}
                </Pie>
                <Tooltip contentStyle={{ backgroundColor: "#0f172a", border: "1px solid #334155", borderRadius: 12 }} />
              </PieChart>
            </ResponsiveContainer>
          </div>
          <div className="grid grid-cols-2 gap-2 text-xs">
            {distribution.map((item) => (
              <div key={item.name} className="flex items-center justify-between rounded-lg bg-slate-900 px-3 py-2 text-slate-300">
                <span className="flex items-center gap-2"><i className="h-2 w-2 rounded-full" style={{ backgroundColor: item.color }} />{item.name}</span>
                <span>{item.value}</span>
              </div>
            ))}
          </div>
        </aside>
      </section>

      <section className="mt-6">
        <VulnerabilityDiffViewer findings={metrics.findings} />
      </section>
    </main>
  );
}

function MetricCard({ label, value, note, icon, tone }: { label: string; value: string; note: string; icon: React.ReactNode; tone: "emerald" | "red" | "orange" | "blue" }) {
  const classes = {
    emerald: "border-emerald-400/20 bg-emerald-400/10 text-emerald-300",
    red: "border-red-400/20 bg-red-400/10 text-red-300",
    orange: "border-orange-400/20 bg-orange-400/10 text-orange-300",
    blue: "border-blue-400/20 bg-blue-400/10 text-blue-300"
  };
  return (
    <article className="rounded-2xl border border-slate-800 bg-slate-950/70 p-5 shadow-panel">
      <div className="flex items-start justify-between"><p className="text-sm text-slate-400">{label}</p><span className={`rounded-lg border p-2 ${classes[tone]}`}>{icon}</span></div>
      <p className="mt-5 text-3xl font-bold text-white">{value}</p>
      <p className="mt-1 text-xs text-slate-500">{note}</p>
    </article>
  );
}
